### ISSUE TITLE
Conditional expression

### ISSUE THREAD

**Issue by svajipay** [opencybersecurityalliance/kestrel-lang#247]
**Is your feature request related to a problem? Please describe.**
We need a IF and some sort of conditional statement execution support in the kestrel-lang. 
**Describe the solution you'd like**
A simple example could be to check for a finding and respond to it. A kestrel analytic can do this internally and return some data to that effect. But all analytics need to do this consistently for threat hunters to act on than just the visual inspection.
**Describe alternatives you've considered**
We can do this in Jupyter note book but only on the data frame.

**Additional context**

**Comment by subbyte** [comment]
We need to better document the current Kestrel way: an empty variable (zero match) will shortcut the huntflow execution that depends on the variable.

We do not have a dedicated condition expression since most of the condition may be expressed in the WHERE clause and we would like Kestrel to execute any flow following the non-empty results. If any variable in a flow is empty, then Kestrel does not need to execute further on that execution/huntflow path. Other branches of the huntflow will continue to be executed though.

@svajipay could you give any additional comments on the current handling strategy? We are planning for syntax upgrade for Kestrel2 and this is one item to go over. An example or use case of the condition expression could be very helpful to discuss.

**Comment by svajipay** [comment]
@subbyte As you know, hunts can take different paths based on whats observed. Supporting branching in a single hunt will be useful. If you think checking of conditions like thresholds/counts etc can be handled within the where clause and that is the recommended approach, please close this request.

**Comment by subbyte** [comment]
Thank you for double check, @svajipay ! We will use our current design (WHERE clause + halting branch execution on empty variable) to handle condition. If you find cases that go beyond this, please reopen the issue and comment.
